# Generated by Django 2.2 on 2021-08-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_items_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
